LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)

LOCAL_MODULE := Bromite
LOCAL_SRC_FILES := arm64_ChromePublic.apk
LOCAL_OVERRIDES_PACKAGES := Browser Browser2 Jelly Chrome-Stub
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_PRODUCT_MODULE := true

include $(BUILD_PREBUILT)